name: Build and Deploy to Production
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{ secrets.API_KEY_PROD }}
          envkey_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN_PROD }}
          envkey_PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
          envkey_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET_PROD }}
          envkey_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID_PROD }}
          envkey_APP_ID: ${{ secrets.APP_ID_PROD }}
          file_name: .env
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
